Models/AppModel.cs
using System;
#nullable disable
namespace TaskApp.Models
{
  public partial  class AppModel
    {
        public int ID {get;set;}
        public string name {get;set;}
        public string Description {get;set;}
        public DateTime Created_at {get;set;}
    }
}

Models/ErrorViewModel.cs
namespace TaskApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/TaskModel.cs
using System;
#nullable disable
namespace TaskApp.Models
{
    public class TaskModel
    {
        public int ID { get; set; }
        public int IdApp { get; set; }
        public string NameTask { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public DateTime Created_at { get; set; }
        public DateTime Updated_at {get;set;}
        
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Context.TaskContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskApp.Models;

namespace TaskApp.Controllers;

public class HomeController : Controller
{
    private readonly TaskContext _context;
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger,TaskContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Index()
    {
        var dataApp =  _context.App.ToList();
        return View(dataApp);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(
            new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
        );
    }

    public async Task<IActionResult> Tareas(int Id){
        var dataTask = await _context.Tasks.Where(x=>x.IdApp ==Id).ToListAsync();
        return View(dataTask);
    }

         public async Task<IActionResult> CreateAppregister([Bind("ID,name,Description")] AppModel appModel)
        {
            if (ModelState.IsValid)
            {
                appModel.Created_at = DateTime.Now;
                _context.Add(appModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return Ok(appModel);
        }
}

Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Context.TaskContext;
using TaskApp.Models;

namespace TaskApp.Controllers
{
    public class TaskController : Controller
    {
        private readonly TaskContext _context;

        public TaskController(TaskContext context)
        {
            _context = context;
        }

        // GET: Task
        public async Task<IActionResult> Index()
        {
              return _context.Tasks != null ? 
                          View(await _context.Tasks.ToListAsync()) :
                          Problem("Entity set 'TaskContext.Tasks'  is null.");
        }

        // GET: Task/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var taskModel = await _context.Tasks
                .FirstOrDefaultAsync(m => m.ID == id);
            if (taskModel == null)
            {
                return NotFound();
            }

            return View(taskModel);
        }

        // GET: Task/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Task/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,NameTask,App,Description")] TaskModel taskModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(taskModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(taskModel);
        }

        // GET: Task/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var taskModel = await _context.Tasks.FindAsync(id);
            if (taskModel == null)
            {
                return NotFound();
            }
            return View(taskModel);
        }

        // POST: Task/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,NameTask,App,Description")] TaskModel taskModel)
        {
            if (id != taskModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taskModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskModelExists(taskModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taskModel);
        }

        // GET: Task/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var taskModel = await _context.Tasks
                .FirstOrDefaultAsync(m => m.ID == id);
            if (taskModel == null)
            {
                return NotFound();
            }

            return View(taskModel);
        }

        // POST: Task/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tasks == null)
            {
                return Problem("Entity set 'TaskContext.Tasks'  is null.");
            }
            var taskModel = await _context.Tasks.FindAsync(id);
            if (taskModel != null)
            {
                _context.Tasks.Remove(taskModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskModelExists(int id)
        {
          return (_context.Tasks?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable<TaskApp.Models.AppModel>
@{
    ViewData["Title"] = "Home Page";
}
<div class="container">
    <div class="d-flex justify-content-start">
        <button type="button" id="btn-add" class="btn btn-outline-secondary" onclick="AddApp();">Add app</button>
    </div>
    <div class="row row-cols-3">
        @if (Model.Count() == 0)
        {
            <div>No se encontraron datos</div>
        }

        @foreach (var item in Model)
        {
            <div class="col">
                <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
                    <div class="card-header">@item.name</div>
                    <div class="card-body">
                        @* <h5 class="card-title">Primary card title</h5> *@
                        <p class="card-text">@item.Description</p>
                        @* <a href="#" class="btn btn-primary">Button</a> *@
                        <a asp-action="Tareas" asp-route-id="@item.ID" class="btn btn-primary">Tareas</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<!-- Vertically centered modal -->
<div class="modal fade" id="ModalAddApp" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">...</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div>
                <form id="formApp">
                    <div class="mb-3">
                        <label for="InputAppName" class="form-label">App Name</label>
                        <input type="text" name="name" class="form-control" id="InputAppName"
                            aria-describedby="appName">
                    </div>
                    <div class="mb-3">
                        <label for="inputDescription" class="form-label">Description</label>
                        <input type="text" name="Description" class="form-control" id="Description">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Understood</button>
        </div>
    </div>
</div>
</div>

@section Scripts{
    <script src="~/js/Home/index.js"></script>
}

Views/Home/Tareas.cshtml
@model IEnumerable<TaskApp.Models.TaskModel>
@{
    ViewData["Title"] = "Tareas";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<div class="row">
@foreach(var item in Model){
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">@item.NameTask</h5>
        <p class="card-text">@item.Description</p>
       <p><span class="badge bg-secondary">@item.State</span></p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
}
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tarea</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/axios/axios.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/app.js"></script>
     <script src="~/js/Task/task.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Task/Create.cshtml
@model TaskApp.Models.TaskModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TaskModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameTask" class="control-label"></label>
                <input asp-for="NameTask" class="form-control" />
                <span asp-validation-for="NameTask" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="App" class="control-label"></label>
                <input asp-for="App" class="form-control" />
                <span asp-validation-for="App" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Task/Delete.cshtml
@model TaskApp.Models.TaskModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameTask)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameTask)
        </dd>
        <dt class = "col-sm-2">
            @* @Html.DisplayNameFor(model => model.App) *@
        </dt>
        <dd class = "col-sm-10">
            @* @Html.DisplayFor(model => model.App) *@
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Task/Details.cshtml
@model TaskApp.Models.TaskModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TaskModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameTask)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameTask)
        </dd>
        <dt class = "col-sm-2">
            @* @Html.DisplayNameFor(model => model.App) *@
        </dt>
        <dd class = "col-sm-10">
            @* @Html.DisplayFor(model => model.App) *@
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Task/Edit.cshtml
@model TaskApp.Models.TaskModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TaskModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="NameTask" class="control-label"></label>
                <input asp-for="NameTask" class="form-control" />
                <span asp-validation-for="NameTask" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="App" class="control-label"></label>
                <input asp-for="App" class="form-control" />
                <span asp-validation-for="App" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Task/Index.cshtml
@model IEnumerable<TaskApp.Models.TaskModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameTask)
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.App) *@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameTask)
            </td>
            <td>
                @* @Html.DisplayFor(modelItem => item.App) *@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>